# cmd: conda build . -c zadorlab -c openbabel -c conda-forge
package:
    name: kinbot
    version: "2.0"

source:
    path: .

build:
    noarch: python

requirements:
    build:
        - python {{ python }}
        - numpy {{ numpy }}
    host:
        - python
    run:
        - python {{ python }}
        - numpy {{ numpy }}
        - matplotlib
        - networkx
        - conda-forge::pyvis
        - zadorlab::ase
        - openbabel::openbabel

about:
    home: https://github.com/zadorlab/KinBot
    license: BSD 3-clause

