# cmd: conda build . -c conda-forge

{% set name = "kinbot" %}
{% set version = "2.0.6" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/zadorlab/KinBot/archive/refs/tags/{{ version }}.tar.gz

build:
    entry_points:
        - kinbot = kinbot.kb:main
        - pes = kinbot.pes:main
    noarch: python

requirements:
    host:
        - python >=3.6
        - setuptools
    run:
        - python >=3.6
        - numpy >=1.17.0
        - matplotlib
        - networkx
        - pyvis
        - openbabel
        - ase

about:
    home: https://github.com/zadorlab/KinBot
    license: BSD 3-clause
    license_file: LICENSE
    summary: Automated reaction pathway search for gas-phase molecules.

extra:
    recipe-maintainers:
        - juditzador
        - cmartia

