# cmd: conda build . -c zadorlab -c rdkit -c openbabel
package:
    name: kinbot
    version: "2.0"

source:
    path: .

requirements:
    build:
        - python
        - numpy
        - matplotlib
        - networkx
        - zadorlab::ase
        - rdkit::rdkit
        - openbabel::openbabel
    run:
        - python
        - numpy
        - matplotlib
        - networkx
        - zadorlab::ase
        - rdkit::rdkit
        - openbabel::openbabel
